initial_packages:
  - oracle-epel-release-el9
  - curl
  - mc
  - wget
  - tar
  - bzip2
  - kernel-devel
  - kernel-headers
  - perl
  - gcc
  - make
  - elfutils-libelf-devel
  - langpacks-en
  - glibc-all-langpacks
  - ca-certificates
  - yum-utils
  - sendmail
  - cockpit-pcp
yum_extra_groups:
  - "@base"
  - "@core"
yum_extra_packages:
  - adcli
  - firefox
  - gcc
  - hdparm
  - iotop
  - krb5-workstation
  - make
  - nmap
  - chrony
  - dkms
  - oddjob
  - oddjob-mkhomedir
  - parted
  - patch
  - realmd
  - samba
  - samba-common
  - screen
  - smartmontools
  - sssd
  - sssd-tools
  - telnet
  - tmux
  - xauth
  - zsh
  - tuned
  - tuned-profiles-atomic
yum_extra_epel_packages:
  - atop
  - bmon
  - gparted
  - htop
  - iftop
  - jq
  - ncdu
  - nmon
  - pv
  - rkhunter
epel_package:
  - oracle-epel-release-el9
selinux:
  state: disabled
webmin:
  - file: webmin
    gpgkey: http://www.webmin.com/jcameron-key.asc
    name: Webmin Distribution Neutral
    timeout: 120
    mirrorlist: http://download.webmin.com/download/yum/mirrorlist
    enabled: 1
neofetch:
  package:
    name: neofetch
  options:
    - option: (\s*[^#]info "Packages" packages).*
      line: '    #info "Packages" packages'
timezone: "UTC"
remote_files:
  - url: https://raw.githubusercontent.com/marcinbojko/hv-packer/master/extra/files/gen2-linux/prepare_neofetch.sh
    dest: /tmp/prepare_neofetch.sh
    mode: "0755"
firewalld:
  default_zone: work
  rich_rules:
    - rule: 'rule family="ipv4" source address="0.0.0.0/0" port port="22" protocol="tcp" accept'
  webmin_rich_rules:
    - rule: 'rule family="ipv4" source address="0.0.0.0/0" port port="10000" protocol="tcp" accept'
  cockpit_rich_rules:
    - rule: 'rule family="ipv4" source address="0.0.0.0/0" port port="9090" protocol="tcp" accept'
  services_remove:
    - ssh
services:
  - name: firewalld
    state: started
    enabled: true
  - name: chronyd
    state: started
    enabled: true
  - name: sshd
    state: started
    enabled: true
  - name: cockpit.socket
    state: started
    enabled: true
  - name: pmlogger.service
    state: started
    enabled: true
sysctl:
  - key: net.ipv4.ip_forward
    value: 1
    state: present
tuned_profile: virtual-guest
locale:
  language: en_US.utf8
  keymap: us
hyperv:
  - name: hypervfcopyd
  - name: hypervkvpd
  - name: hypervvssd
motd: |
  #!/bin/bash
  neofetch --config /etc/neofetch/config.conf
  if [ -f ~/.Xauthority ]; then
    xauth merge ~/.Xauthority
  fi
  export XAUTHORITY=$HOME/.Xauthority
  export PATH="/usr/local/bin:$PATH"
kernel_parameters:
  - key: "fsck.repair"
    value: "yes"
    state: present

